apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-nginx
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - port: 80
      protocol: TCP
  podSelector:
    matchLabels:
      {{- include "template.client.selectorLabels" . | nindent 4 }}
      {{- include "template.server.selectorLabels" . | nindent 4 }}
  policyTypes:
  - Ingress
