{{- if .Values.vso.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tls
spec:
  vaultAuthRef: vault-auth
  mount: tobi
  path: tls
  type: kv-v2
  destination:
    name: tuto-mono.apps.ari.np.internal.auchan.com
    create: true
{{- end -}}
